using Singularity.Vector;
using Singularity.Apps.Vector;

PathNode filled (PathData p, string fill, string? stroke = null, double width = 2) {
    var n = new PathNode.with_path (p);
    n.appearance.add (new PaintLayer.fill (new Paint.hex (fill)));
    if (stroke != null) n.appearance.add (new PaintLayer.line (new Paint.hex (stroke), width));
    return n;
}

TextNode label (string text, double x, double y) {
    var t = new TextNode ();
    t.text = text;
    t.style.size = 13;
    t.matrix = Transforms.translate (x, y);
    t.appearance.add (new PaintLayer.fill (new Paint.hex ("#333333")));
    return t;
}

int page_two (string out_path) {
    var d = VectorDocument.blank (1200, 700);
    var layer = d.active_layer;
    var paths = new Gee.ArrayList<PathData> ();
    paths.add (new PathData.ellipse (110, 110, 70, 70));
    paths.add (new PathData.ellipse (190, 110, 70, 70));
    paths.add (new PathData.ellipse (150, 170, 70, 70));
    string[] colors = { "#1d71b8", "#e5322d", "#ffed00", "#3aaa35", "#951b81", "#f39200", "#009fa0" };
    int ci = 0;
    foreach (var face in new Arrangement (paths).faces ()) layer.add (filled (face.path, colors[ci++ % colors.length], "#ffffff", 2));
    layer.add (label ("Divide: 7 regions", 90, 280));
    var lp = new LivePaintNode ();
    var l1 = new PathNode.with_path (new PathData.rect (330, 50, 200, 200));
    l1.appearance.add (new PaintLayer.line (new Paint.hex ("#222222"), 2));
    var l2 = new PathNode ();
    l2.path.move_to (330, 50);
    l2.path.line_to (530, 250);
    l2.appearance.add (new PaintLayer.line (new Paint.hex ("#222222"), 2));
    var l3 = new PathNode ();
    l3.path.move_to (530, 50);
    l3.path.line_to (330, 250);
    l3.appearance.add (new PaintLayer.line (new Paint.hex ("#222222"), 2));
    lp.add (l1);
    lp.add (l2);
    lp.add (l3);
    lp.paint_at (Point (430, 80), new Paint.hex ("#f39200"));
    lp.paint_at (Point (430, 220), new Paint.hex ("#1d71b8"));
    lp.paint_at (Point (360, 150), new Paint.hex ("#3aaa35"));
    layer.add (lp);
    layer.add (label ("Live Paint on open lines", 360, 280));
    var env = new EnvelopeNode ();
    var t = new TextNode ();
    t.text = "WARP";
    t.style.size = 72;
    t.style.weight = 800;
    t.matrix = Transforms.translate (600, 180);
    t.appearance.add (new PaintLayer.fill (new Paint.hex ("#e6007e")));
    env.add (t);
    env.style = "arc";
    env.bend = 0.5;
    layer.add (env);
    layer.add (label ("Envelope Arc on text", 640, 280));
    var rep = new RepeatNode ();
    var petal = filled (new PathData.ellipse (1000, 70, 14, 34), "#3c3c8f");
    petal.opacity = 0.8;
    rep.add (petal);
    rep.radius = 70;
    rep.count = 12;
    layer.add (rep);
    layer.add (label ("Radial Repeat", 960, 280));
    int w = 120, h = 120, stride = w * 4;
    var data = new uint8[stride * h];
    for (int y = 0; y < h; y++) for (int x = 0; x < w; x++) {
        int o = y * stride + x * 4;
        double r = Math.hypot (x - 60, y - 60);
        bool ring = r > 30 && r < 50;
        bool bar = (x - y).abs () < 8;
        uint8 v = ring || bar ? 30 : 250;
        data[o] = data[o + 1] = data[o + 2] = v;
        data[o + 3] = 255;
    }
    var traced = BitmapTrace.trace (data, w, h, stride, new TraceOptions ());
    foreach (var tl in traced) {
        var tp = filled (tl.path, "#111111");
        tp.apply_transform (Transforms.translate (80, 360));
        layer.add (tp);
    }
    layer.add (label ("Image Trace", 100, 520));
    var a = filled (new PathData.rect (330, 360, 120, 120), "#ffed00", "#000000", 2);
    var b = filled (new PathData.ellipse (450, 420, 60, 60), "#009fa0", "#000000", 2);
    var sub = new Gee.ArrayList<PathData> ();
    sub.add (a.path);
    sub.add (b.path);
    var minus = CurveBoolean.combine (sub, BoolOp.SUBTRACT);
    layer.add (filled (minus, "#ffed00", "#000000", 2));
    layer.add (label ("Minus Front", 360, 520));
    var chart = new ChartNode ();
    chart.x = 600;
    chart.y = 340;
    chart.w = 300;
    chart.h = 180;
    layer.add (chart);
    layer.add (label ("Column Graph", 690, 540));
    var rev = new Shape3DNode ();
    rev.mode = "revolve";
    rev.profile = PathData.parse_svg ("M1000 360 C1040 380 1020 420 1050 460 L1050 500");
    rev.rx = -20;
    rev.ry = 0;
    rev.rz = 0;
    rev.appearance.add (new PaintLayer.fill (new Paint.hex ("#e5322d")));
    layer.add (rev);
    layer.add (label ("3D Revolve", 980, 540));
    d.ensure_ids ();
    var img = Renderer.render_image (d, Rect (0, 0, 1200, 570), 1, false);
    img.write_to_png (out_path);
    print ("%s\n", out_path);
    return 0;
}

int page_three (string out_path) {
    var d = VectorDocument.blank (1200, 700);
    var r = new PathNode ();
    r.live = new LiveShape ();
    r.live.kind = "rectangle";
    r.live.cx = 975;
    r.live.cy = 360;
    r.live.w = 350;
    r.live.h = 320;
    r.rebuild_live ();
    r.appearance.add (new PaintLayer.fill (new Paint.hex ("#ffffff")));
    r.appearance.add (new PaintLayer.line (new Paint.hex ("#000000"), 1));
    var p = new Paint ();
    p.kind = PaintKind.RADIAL;
    p.gradient = new Gradient ();
    p.gradient.stops.add (new GradientStop (0, Ink.hex ("#ffffff")));
    p.gradient.stops.add (new GradientStop (0.5, Ink.hex ("#e6007e")));
    p.gradient.stops.add (new GradientStop (1, Ink.hex ("#951b81")));
    Transforms.fit_gradient (p, r.geometric_bounds ());
    r.appearance[0].paint = p;
    r.effects.add (new Effect ("drop-shadow").set_num ("dx", 10).set_num ("dy", 12).set_num ("blur", 10).set_num ("opacity", 0.4).set_str ("color", "#000000"));
    d.active_layer.add (r);
    d.ensure_ids ();
    var rec = new Cairo.RecordingSurface (Cairo.Content.COLOR_ALPHA, null);
    var cr = new Cairo.Context (rec);
    cr.scale (0.52, 0.52);
    cr.translate (40, 40);
    var ctx = new RenderContext (d);
    Renderer.draw_document (cr, ctx);
    var img = new Cairo.ImageSurface (Cairo.Format.ARGB32, 800, 500);
    var ic = new Cairo.Context (img);
    ic.set_source_rgb (1, 1, 1);
    ic.paint ();
    ic.set_source_surface (rec, 0, 0);
    ic.paint ();
    img.write_to_png (out_path);
    print ("%s %s\n", out_path, cr.status ().to_string ());
    return 0;
}

int main (string[] args) {
    if (args.length > 2 && args[2] == "3") return page_three (args[1]);
    if (args.length > 2 && args[2] == "2") return page_two (args[1]);
    var d = VectorDocument.blank (1200, 800);
    var layer = d.active_layer;
    var c1 = new PathData.ellipse (90, 110, 55, 55);
    var c2 = new PathData.ellipse (150, 110, 55, 55);
    layer.add (filled (CurveBoolean.apply (c1, c2, BoolOp.UNION), "#1d71b8", "#0b3a66", 3));
    layer.add (label ("Union", 60, 200));
    layer.add (filled (CurveBoolean.apply (c1.transformed (Transforms.translate (220, 0)), c2.transformed (Transforms.translate (220, 0)), BoolOp.EXCLUDE), "#e5322d", "#7a1210", 3));
    layer.add (label ("Exclude", 285, 200));
    var star = new PathNode ();
    star.live = new LiveShape ();
    star.live.kind = "star";
    star.live.cx = 560;
    star.live.cy = 110;
    star.live.w = 120;
    star.live.h = 120;
    star.live.sides = 5;
    star.live.inner = 0.45;
    star.rebuild_live ();
    layer.add (filled (CurveOffset.offset (star.path, 14, JoinKind.ROUND), "#ffed00"));
    layer.add (filled (star.path, "#f39200"));
    layer.add (label ("Offset Path", 520, 200));
    var wave = new PathData ();
    wave.move_to (660, 110);
    wave.curve_to (700, 30, 760, 190, 800, 110);
    var outline = CurveOffset.stroke (wave, 22, JoinKind.ROUND, CapKind.ROUND);
    layer.add (filled (outline, "#3aaa35", "#145214", 1.5));
    layer.add (label ("Outline Stroke", 680, 200));
    var grad = filled (new PathData.round_rect (860, 50, 140, 120, 18), "#000000");
    grad.appearance[0].paint.kind = PaintKind.RADIAL;
    grad.appearance[0].paint.gradient = new Gradient.two (Ink.hex ("#ffffff"), Ink.hex ("#951b81"));
    grad.appearance[0].paint.gradient.stops.insert (1, new GradientStop (0.5, Ink.hex ("#e6007e")));
    Transforms.fit_gradient (grad.appearance[0].paint, Rect (860, 50, 140, 120));
    grad.effects.add (new Effect ("drop-shadow").set_num ("dx", 6).set_num ("dy", 8).set_num ("blur", 6).set_num ("opacity", 0.45));
    layer.add (grad);
    layer.add (label ("Radial + Shadow", 880, 200));
    var mesh = new MeshNode ();
    mesh.init_grid (Rect (40, 260, 180, 140), 2, 2, Ink.hex ("#ffffff"));
    mesh.at (0, 0).color = Ink.hex ("#1d71b8");
    mesh.at (0, 2).color = Ink.hex ("#ffed00");
    mesh.at (2, 0).color = Ink.hex ("#e5322d");
    mesh.at (2, 2).color = Ink.hex ("#3aaa35");
    mesh.move_vertex (1, 1, 20, -15);
    layer.add (mesh);
    layer.add (label ("Gradient Mesh", 80, 420));
    var blend = new BlendNode ();
    var a = filled (new PathData.ellipse (290, 330, 30, 30), "#1d71b8");
    var b = filled (new PathData.rect (420, 280, 80, 80), "#f39200");
    blend.add (a);
    blend.add (b);
    blend.steps = 6;
    layer.add (blend);
    layer.add (label ("Blend", 360, 420));
    var tp = new TextNode ();
    tp.mode = "path";
    tp.text = "Text follows any path";
    tp.style.size = 20;
    tp.on_path = new PathData ();
    tp.on_path.move_to (560, 380);
    tp.on_path.curve_to (600, 260, 760, 260, 800, 380);
    tp.appearance.add (new PaintLayer.fill (new Paint.hex ("#3c3c8f")));
    layer.add (tp);
    var guide = new PathNode.with_path (tp.on_path.copy ());
    guide.appearance.add (new PaintLayer.line (new Paint.hex ("#bbbbbb"), 1));
    layer.add (guide);
    layer.add (label ("Text on Path", 630, 420));
    var vw = new PathData ();
    vw.move_to (860, 330);
    vw.curve_to (920, 260, 980, 400, 1060, 320);
    var vn = new PathNode.with_path (vw);
    var stroke = new PaintLayer.line (new Paint.hex ("#009fa0"), 24);
    stroke.profile.add (new WidthPoint (0, 0.05, 0.05));
    stroke.profile.add (new WidthPoint (0.5, 1, 1));
    stroke.profile.add (new WidthPoint (1, 0.05, 0.05));
    vn.appearance.add (stroke);
    layer.add (vn);
    layer.add (label ("Width Profile", 900, 420));
    var pat = new PatternDef ();
    pat.id = "pat1";
    pat.w = 20;
    pat.h = 20;
    pat.tiling = "brick-row";
    pat.tile.add (filled (new PathData.ellipse (10, 10, 6, 6), "#e6007e"));
    d.patterns.add (pat);
    var pn = filled (new PathData.rect (40, 480, 180, 140), "#000000");
    pn.appearance[0].paint.kind = PaintKind.PATTERN;
    pn.appearance[0].paint.pattern = "pat1";
    pn.appearance.add (new PaintLayer.line (new Paint.hex ("#333333"), 2));
    layer.add (pn);
    layer.add (label ("Pattern Fill", 90, 640));
    var art = new PathData ();
    art.move_to (280, 560);
    art.curve_to (330, 470, 420, 650, 480, 540);
    var an = new PathNode.with_path (art);
    var brush_layer = new PaintLayer.line (new Paint.hex ("#8b5a2b"), 6);
    brush_layer.brush = d.brushes[1].id;
    an.appearance.add (brush_layer);
    layer.add (an);
    var cal = new PathData ();
    cal.move_to (280, 610);
    cal.curve_to (330, 560, 420, 680, 480, 600);
    var cn = new PathNode.with_path (cal);
    var cal_layer = new PaintLayer.line (new Paint.hex ("#000000"), 2);
    cal_layer.brush = d.brushes[0].id;
    cn.appearance.add (cal_layer);
    layer.add (cn);
    layer.add (label ("Art and Calligraphic Brushes", 290, 640));
    var mask_target = filled (new PathData.rect (560, 470, 220, 150), "#1d71b8");
    var mask_art = filled (new PathData.rect (560, 470, 220, 150), "#000000");
    mask_art.appearance[0].paint.kind = PaintKind.LINEAR;
    mask_art.appearance[0].paint.gradient = new Gradient.two (Ink.hex ("#ffffff"), Ink.hex ("#000000"));
    Transforms.fit_gradient (mask_art.appearance[0].paint, Rect (560, 470, 220, 150));
    mask_target.mask = mask_art;
    layer.add (mask_target);
    layer.add (label ("Opacity Mask", 620, 640));
    var s3 = new Shape3DNode ();
    s3.profile = new PathData.round_rect (870, 490, 120, 90, 14);
    s3.depth = 60;
    s3.appearance.add (new PaintLayer.fill (new Paint.hex ("#f39200")));
    layer.add (s3);
    layer.add (label ("3D Extrude", 900, 640));
    d.ensure_ids ();
    var img = Renderer.render_image (d, Rect (0, 0, 1200, 680), 1, false);
    string out_path = args.length > 1 ? args[1] : "showcase.png";
    img.write_to_png (out_path);
    print ("%s\n", out_path);
    return 0;
}
